# Title of the document
title: "网易云课堂数据分析报告"

# Per variable type description settings
vars:
    num:
          quantiles:
                - 0.05
                - 0.25
                - 0.5
                - 0.75
                - 0.95
          skewness_threshold: 20
          low_categorical_threshold: 5
    cat:
        check_composition: True
        cardinality_threshold: 50
        n_obs: 5
    bool:
        n_obs: 3

# Sort the variables. Possible values: ascending, descending or None (leaves original sorting)
sort: ascending

# which diagrams to show
missing_diagrams:
    bar: True
    matrix: True
    heatmap: True
    dendrogram: True

correlations:
    pearson:
      calculate: True
      warn_high_correlations: True
      threshold: 0.9
    spearman:
      calculate: True
      warn_high_correlations: False
    kendall:
      calculate: True
      warn_high_correlations: False
    phi_k:
      calculate: True
      warn_high_correlations: False
    cramers:
      calculate: True
      warn_high_correlations: True
      threshold: 0.9
    recoded:
      calculate: True
      warn_high_correlations: True
      threshold: 1.0

# For categorical
categorical_maximum_correlation_distinct: 100

# Plot-specific settings
plot:
# Image format (svg or png)
    image_format: "svg"
    dpi: 800

    correlation:
        cmap: 'bwr'

    missing:
        cmap: 'RdBu'

    histogram:
# is used for numeric variables
        bayesian_blocks_bins: True

# If 'bayesian_blocks_bins' fails to provide a valid number of bins.
        bins: 50
# Also used for equal size histogram

# The number of observations to show
n_obs_unique: 5
n_extreme_obs: 5
n_freq_table_max: 10